var date = new Date();
var currentYear = date.getFullYear();
var currentDate = date.getDate();
var currentMonth = date.getMonth() + 1;
var options = { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric'};
var formattedDate = date.toLocaleDateString('en-US', options);
document.getElementById("currentYear").textContent = currentYear;
document.getElementById("lastModified").textContent = document.lastModified;
document.getElementById("lastTime").textContent = formattedDate;
